mc-imperial/dredd

- .github/workflows/dev_build.sh
- scripts/check_build.sh
- scripts/check_compile_commands.sh
- src/.clang-tidy
- src/dredd/src/main.cc
- src/libdredd/CMakeLists.txt
- src/libdredd/include/libdredd/mersenne_random_generator.h
- src/libdredd/include/libdredd/mutation_replace_eager_binary_operator.h
- src/libdredd/include/libdredd/new_mutate_frontend_action_factory.h
- src/libdredd/include/libdredd/random_generator.h
- src/libdredd/include_private/include/libdredd/mutate_ast_consumer.h
- src/libdredd/include_private/include/libdredd/mutate_visitor.h
- src/libdredd/src/mersenne_random_generator.cc
- src/libdredd/src/mutate_ast_consumer.cc
- src/libdredd/src/mutate_visitor.cc
- src/libdredd/src/mutation_replace_eager_binary_operator.cc
- src/libdredd/src/new_mutate_frontend_action_factory.cc
- src/libdredd/src/random_generator.cc
- src/libdreddtest/.clang-tidy
- src/libdreddtest/src/mutation_replace_eager_binary_operator_test.cc
Properly configures clang-tidy, fixing many associated warnings.
Adds a random number generation interface and uses it to make
operator replacement randomized.
Fixes #7.
> Configure clang-tidy and various improvements

- src/libdredd/include_private/include/libdredd/mutate_visitor.h
- src/libdredd/src/mutate_ast_consumer.cc
- src/libdredd/src/mutate_visitor.cc
- src/libdredd/src/mutation_replace_binary_operator.cc
- src/libdredd/src/new_mutate_frontend_action_factory.cc
- src/libdreddtest/src/mutation_replace_binary_operator_test.cc
Dredd now copes with multiple instances of a file cropping up, avoids
the use of a global variable for the enabled mutation, and adds
necessary includes and common function declarations at the top of the
translation unit.
> Various improvements

- src/libdredd/CMakeLists.txt
- src/libdredd/include/libdredd/mutation.h
- src/libdredd/include/libdredd/mutation_remove_statement.h
- src/libdredd/include/libdredd/mutation_replace_binary_operator.h
- src/libdredd/include_private/include/libdredd/mutate_ast_consumer.h
- src/libdredd/include_private/include/libdredd/mutate_visitor.h
- src/libdredd/include_private/include/libdredd/util.h
- src/libdredd/src/mutate_ast_consumer.cc
- src/libdredd/src/mutate_visitor.cc
- src/libdredd/src/mutation_remove_statement.cc
- src/libdredd/src/mutation_replace_binary_operator.cc
- src/libdreddtest/src/mutation_remove_statement_test.cc
- src/libdreddtest/src/mutation_replace_binary_operator_test.cc
Refines the machinery for checking whether AST nodes start and end in
the main file, to support macros.
Fixes #23.
> Allow mutations in certain macro contexts

- examples/simple/pi.cc
- scripts/check_format.sh
- scripts/examples_cmake_files.sh
- scripts/examples_source_files.sh
Extends the Dredd format checking and fixing scripts to consider code
under the 'examples' directory.
> Check formatting of examples

- src/libdredd/src/mutate_visitor.cc
Fixes an issue where a mutation would be applied despite the innermost
enclosing declaration not being a function.
> Only mutate when inside a function

- src/libdredd/src/mutation_replace_binary_operator.cc
- src/libdreddtest/src/mutation_replace_binary_operator_test.cc
Updated operator replacement to always use lambdas to more faithfully
mimic the mutation having been applied to the source code.
Fixed #34.
> Updated operator replacement to use lambdas.

- scripts/check_all.sh
- scripts/check_headers.py
- scripts/check_single_file_tests.sh
- scripts/regenerate_single_file_expectations.sh
- test/single_file/README.md
- test/single_file/basic.cc
- test/single_file/basic.expected
- test/single_file/constexpr.cc
- test/single_file/constexpr.expected
Adds a script and corresponding initial tests to allow confirming that
Dredd performs as expected on a number of single-file test cases.
Fixes #45.
> Add single-file test framework

- src/libdredd/include/libdredd/mutation.h
- src/libdredd/include/libdredd/mutation_remove_statement.h
- src/libdredd/include/libdredd/mutation_replace_binary_operator.h
- src/libdredd/src/mutate_ast_consumer.cc
- src/libdredd/src/mutate_visitor.cc
- src/libdredd/src/mutation_remove_statement.cc
- src/libdredd/src/mutation_replace_binary_operator.cc
- src/libdreddtest/.clang-tidy
- src/libdreddtest/src/mutation_remove_statement_test.cc
- src/libdreddtest/src/mutation_replace_binary_operator_test.cc
- test/single_file/add.cc
- test/single_file/add.expected
- test/single_file/add_mul.cc
- test/single_file/add_mul.expected
- test/single_file/add_type_aliases.cc
- test/single_file/add_type_aliases.expected
- test/single_file/constexpr.expected
Reworks binary operator mutation to avoid producing a separate
function for every single operator that is considered. Instead,operators with common argument types share the same mutation function (if in the same source file).
Fixes #48.
> Avoid duplicate mutation functions

- src/libdredd/src/mutation_replace_binary_operator.cc
- test/single_file/volatile.cc
- test/single_file/volatile.expected
Properly account for volatile when mutating binary operators.
Fixes #51.
> Handle volatile in binary operator mutation

- src/libdredd/src/mutate_ast_consumer.cc
- src/libdredd/src/mutation_remove_statement.cc
- src/libdredd/src/mutation_replace_binary_operator.cc
- src/libdreddtest/src/mutation_remove_statement_test.cc
- src/libdreddtest/src/mutation_replace_binary_operator_test.cc
- test/single_file/add.expected
- test/single_file/add_mul.expected
- test/single_file/add_type_aliases.expected
- test/single_file/basic.expected
Paves the way for enabling multiple mutants, by using a predicate to
check whether a mutation is enabled, rather than asking which
particualr mutant is enabled.
Part of #55.
> Check enabled mutation using predicate

- src/libdredd/include/libdredd/mutation.h
- src/libdredd/include/libdredd/mutation_remove_statement.h
- src/libdredd/include/libdredd/mutation_replace_binary_operator.h
- src/libdredd/src/mutate_ast_consumer.cc
- src/libdredd/src/mutation_remove_statement.cc
- src/libdredd/src/mutation_replace_binary_operator.cc
- src/libdreddtest/src/mutation_remove_statement_test.cc
- src/libdreddtest/src/mutation_replace_binary_operator_test.cc
- test/single_file/add.expected
- test/single_file/add_mul.expected
- test/single_file/add_type_aliases.expected
- test/single_file/basic.expected
- test/single_file/volatile.expected
Paving the way for having multiple mutants enabled, this change
introduces an array of booleans to track the mutations that are
enabled on a per file basis. At present, at most one element of this
array will be set to true. In a future change, environment variable
parsing will be updated to support multiple mutants.
Part of #55.
> Use bool array to track which mutants are enabled

- src/libdredd/src/mutate_ast_consumer.cc
- test/single_file/add.expected
- test/single_file/add_mul.expected
- test/single_file/add_type_aliases.expected
- test/single_file/basic.expected
- test/single_file/volatile.expected
Replaces array of booleans with bitset for tracking of enabled
mutants, which is more space-efficient.
Part of #55.
> Use bitset for enabled mutants

- src/libdredd/include/libdredd/mutation_replace_binary_operator.h
- src/libdredd/src/mutation_replace_binary_operator.cc
- test/single_file/volatile.expected
Separate binary function name generation into it's own function to 
make the Apply function easier to understand.
> Refactor binary function name generation

- src/libdredd/src/mutate_ast_consumer.cc
- test/single_file/define_in_first_decl.cc
- test/single_file/define_in_first_decl.expected
Fixes Dredd so that the source range in the main file is obtained for
the first declaration occurring in that file, before inserting Dredd's
prelude. This avoids a problem where if the first declaration starts
with a macro expansion, its begin location is not valid for an
insertion.
Fixes #66.
> Fix rewriting error before first declaration

- src/libdredd/include_private/include/libdredd/mutate_visitor.h
- src/libdredd/src/mutate_visitor.cc
- test/single_file/negative_switch_case.cc
- test/single_file/negative_switch_case.expected
Switch case expressions need to be constants and so cannot easily
mutated in the Dredd style.
Fixes #68.
> Do not mutate switch case expressions

- src/libdredd/include_private/include/libdredd/mutate_visitor.h
- src/libdredd/src/mutate_ast_consumer.cc
- src/libdredd/src/mutate_visitor.cc
- test/single_file/template.cc
- test/single_file/template.expected
- test/single_file/typedef.cc
- test/single_file/typedef.expected
- test/single_file/using.cc
- test/single_file/using.expected
Changes the logic for deciding where to insert the Dredd prelude to
account for the fact that the first declaration encountered when
visiting the AST may not correspond to the declaration whose start
appears syntactically earliest in the main source file.
Fixes #70.
> Correct where Dredd prelude is inserted

- src/libdredd/src/mutate_visitor.cc
- test/single_file/bitfield.cc
- test/single_file/bitfield.expected
As it is not possible to pass bit-fields by refernce, mutations cannot
be applied to bit-field l-values.
Fixes #73.
> Do not mutate operators that use bit-field l-values

- src/libdredd/src/mutation_remove_statement.cc
- test/single_file/comment.cc
- test/single_file/comment.expected
Ensures that comments are accounted for when extending statement
source ranges to include trailing semi-colons during statement
deletion.
Fixes #72.
> Account for comments when removing return statements

- src/libdredd/include_private/include/libdredd/mutate_visitor.h
- src/libdredd/src/mutate_visitor.cc
- test/single_file/template_instantiation.cc
- test/single_file/template_instantiation.cc.expected
Avoids mutating template argument expressions, which normally need to
be compile-time constants.
Fixes #80.
> Do not mutate template arguments

- src/libdredd/src/mutate_visitor.cc
- test/single_file/parens.cc
- test/single_file/parens.cc.expected
Avoids mutating expressions of the form (e), since mutating e suffices.
Fixes #99.
> Do not mutate parentheses expressions

- scripts/check_cmakelint.sh
- scripts/check_format.sh
- scripts/check_one_single_file_test.sh
- scripts/check_single_file_tests.sh
- scripts/fix_format.sh
- scripts/regenerate_one_single_file_expectation.sh
- scripts/regenerate_single_file_expectations.sh
Avoids duplication in the scripts for checking and regenerating
single-file tests and expectations.
Fixes #113.
> Refactor scripts for handling single-file tests

- src/dredd/src/main.cc
- src/libdredd/include/libdredd/new_mutate_frontend_action_factory.h
- src/libdredd/include_private/include/libdredd/mutate_ast_consumer.h
- src/libdredd/src/mutate_ast_consumer.cc
- src/libdredd/src/new_mutate_frontend_action_factory.cc
It is very useful to be able to dump ASTs when debugging; this adds a command line option, --dump-asts, to enable it.
> Add command line option for dumping ASTs

- src/libdredd/src/mutation_replace_expr.cc
Fixes an issue where the result type was being used for what should have been the input type of a lambda.
> Fix type used in lambda

- src/libdredd/src/mutate_visitor.cc
- test/single_file/add_float.c.expected
- test/single_file/add_float.cc.expected
- test/single_file/floats.c.expected
- test/single_file/floats.cc.expected
- test/single_file/positive_int_as_minus_one.c.expected
- test/single_file/positive_int_as_minus_one.cc.expected
- test/single_file/unary.c.expected
- test/single_file/unary.cc.expected
- test/single_file/unary_logical_not.c.expected
- test/single_file/unary_logical_not.cc.expected
- test/single_file/unsigned_int.c.expected
- test/single_file/unsigned_int.cc.expected
Restricts mutation of cast expressions to the case where the expression inside the case is an l-value and the cast expression is an r-value. This avoids a large number of cases where literal values are implicitly case from signed to unsigned, or from double to float, and get mutated twice as a result.
Fixes #121.
> Restrict mutation of cast expressions

- src/libdredd/src/mutate_visitor.cc
- test/single_file/add_float.c.expected
- test/single_file/assign.c.expected
- test/single_file/binary_operands_both_zero.c.expected
- test/single_file/bitfield.c.expected
- test/single_file/bitfield.cc.expected
- test/single_file/expr_lvalue.c.expected
- test/single_file/floats.c.expected
- test/single_file/post_inc_volatile.c.expected
- test/single_file/printing.c.expected
- test/single_file/unary.c.expected
- test/single_file/unary.cc.expected
- test/single_file/volatile.c.expected
Avoid applying general expression mutation to top-level expression statements that appear in compound statements, as there is little-to-no value in doing so.
Fixes #93.
> Do not mutate top-level expressions in blocks

- src/libdredd/include_private/include/libdredd/mutate_visitor.h
- src/libdredd/include_private/include/libdredd/mutation_tree_node.h
- src/libdredd/src/mutate_ast_consumer.cc
- src/libdredd/src/mutation_tree_node.cc
Fixes a problem where a pointer to a vector element was being leaked, leading to problems when the vector was resized.
> Fix memory corruption issue

- src/libdredd/src/mutate_visitor.cc
- test/single_file/add_float.c.expected
- test/single_file/add_float.cc.expected
- test/single_file/enum.c.expected
- test/single_file/floats.c.expected
- test/single_file/floats.cc.expected
- test/single_file/initializer_list.cc.expected
- test/single_file/positive_int_as_minus_one.c.expected
- test/single_file/positive_int_as_minus_one.cc.expected
- test/single_file/unary.c.expected
- test/single_file/unary.cc.expected
- test/single_file/unary_logical_not.c.expected
- test/single_file/unary_logical_not.cc.expected
- test/single_file/unsigned_int.c.expected
- test/single_file/unsigned_int.cc.expected
This change means that only the outermost expression in a nest of casts will be mutated, rather than the target of the innermost cast. In an l-value to r-value cast, both the result of the cast and the cast operand are still mutated.
Fixes #115.
> Favour mutating outside vs. inside casts

- src/libdredd/src/mutation_remove_statement.cc
- src/libdredd/src/mutation_replace_expr.cc
- src/libdredd/src/mutation_replace_unary_operator.cc
- src/libdredd/src/new_mutate_frontend_action_factory.cc
Avoids a couple of (void) casts for parameters that are now used. Tidies up punctuation in related comments.
> Remove unnecessary "unused" casts

- src/libdredd/CMakeLists.txt
- src/libdredd/include/libdredd/mutation_remove_stmt.h
- src/libdredd/src/mutate_visitor.cc
- src/libdredd/src/mutation_remove_stmt.cc
- src/libdreddtest/CMakeLists.txt
- src/libdreddtest/src/mutation_remove_stmt_test.cc
- src/libdreddtest/src/mutation_replace_expr_test.cc
In the expression-related mutations, "expr" is used instead of "expression", which matches Clang. This change brings "statement" in to line by changing it to "stmt".
> Rename MutationRemoveStatement to MutationRemoveStmt

- scripts/dredd_cmake_files.sh
- third_party/googletest/CMakeLists.txt
Includes the intermediate CMakeLists.txt file for the googletest third party repo in the files that are checked for formatting requirements.
> Update CMake formatting to include googletest

- src/libdredd/include/libdredd/mutation_replace_binary_operator.h
- src/libdredd/include/libdredd/mutation_replace_unary_operator.h
- src/libdredd/include/libdredd/protobufs/dredd.proto
- src/libdredd/src/mutation_replace_binary_operator.cc
- src/libdredd/src/mutation_replace_unary_operator.cc
Allows recording the unary/binary operator associated with a mutated expression in the corresponding protobuf message.
> Add unary and binary operators to protobufs

- .github/workflows/build.sh
- .github/workflows/build.yml
- .github/workflows/c_apps.sh
- .github/workflows/cxx_apps.sh
- .github/workflows/dev_build.sh
- .github/workflows/release.sh
- .github/workflows/release.yml
- README.md
- dev_shell.sh.template
- scripts/llvm_tag.sh
- third_party/.gitignore
Due to problems getting stable releases of Clang/LLVM via the
build-clang repo, reverting to an older version that is available for
Linux in pre-built form via the LLVM GitHub project.
> Revert to older version of Clang/LLVM

- src/libdredd/include/libdredd/mutation_replace_unary_operator.h
- src/libdredd/src/mutation_replace_unary_operator.cc
- src/libdreddtest/src/mutation_replace_unary_operator_test.cc
- test/single_file/post_inc_volatile.c.expected
- test/single_file/post_inc_volatile.cc.expected
- test/single_file/pre_dec_assign.cc.expected
- test/single_file/unary.c.expected
- test/single_file/unary.cc.expected
- test/single_file/unary_operator_opt.c.expected
- test/single_file/unsigned_int.c.expected
- test/single_file/unsigned_int.cc.expected
Self-inverse unary operator removal is equivalent to insertion of another instance of the unary operator, so is is redundant to perform both mutations.
This change avoids the need for some checks to decide when operator removal was redudant due to expressions having constant values. That code had been identified to be buggy, which its removal also fixes.
Fixes #97.
Fixes #158.
> Do not remove self-inverse unary operators

- .github/workflows/c_apps.sh
- .github/workflows/cxx_apps.sh
A bash mistake meant that Dredd was only being applied to one file per project.
> Fix issue with C/C++ apps in CI

- src/dredd/src/main.cc
- src/libdredd/src/mutation_replace_expr.cc
Fixes a problem where too many 'instance' entries were being added for certain mutations, and changes protobuf JSON export so that primitive values are always represented even if they are zero.
> Fix protobuf issues

- src/libdredd/src/mutate_ast_consumer.cc
- test/single_file/misc002.cc
- test/single_file/misc002.cc.expected
- test/single_file/misc002.cc.noopt.expected
No mutation was being applied to a trivial equality test. Decided to commit to simplifying the design of Dredd to avoid the requirement that every generated mutation object will lead to at least one runtime mutation.
Related issue: #171
> Resolved issue where no mutation was applied

- .github/workflows/cxx_apps.sh
Update CI to use a more recent version of SPIR-V Tools when testing C++ apps.
> Update SPIR-V Tools

- .github/workflows/cxx_apps.sh
Update CI to use Clang 17 as a target for mutation in C++ apps.
> Update Clang in C++ apps

- .github/workflows/build.yml
Change the way python is installed in build.yml and switch back to an x86 version of macOS.
Fixes #227.
> Fix macOS CI build

- src/libdredd/src/mutate_visitor.cc
- src/libdredd/src/mutation_replace_binary_operator.cc
- test/single_file/binary_both_zero.cc
- test/single_file/binary_both_zero.cc.expected
- test/single_file/binary_both_zero.cc.noopt.expected
- test/single_file/braced_initialization.cc
- test/single_file/braced_initialization.cc.expected
- test/single_file/braced_initialization.cc.noopt.expected
Previously, when mutating expressions such as `char test {24}`, the braced initialization expression `{24}` would also get mutated (as noted in #225). This lead to compilation errors. This is resolved by avoiding the mutation of `InitListExpr`.
Also, the optimization checks for the case when both arguments to a binary expression were zero was previously wrong (as noted in #222). This is resolved.
Fixes: #222, #225.
> Fix braced initalization and binary zero optimizations

- src/libdredd/src/mutate_visitor.cc
- test/single_file/const_expr_function.cc
- test/single_file/const_expr_function.cc.expected
- test/single_file/const_expr_function.cc.noopt.expected
- test/single_file/const_expr_function_call.cc
- test/single_file/const_expr_function_call.cc.expected
- test/single_file/const_expr_function_call.cc.noopt.expected
We cannot mutate functions that are specified as constexpr as Dredd's mutations occur dynamically and constexpr functions require compile time evaluation.
Fixes: #233.
> Avoid mutation constexpr specified functions

- src/libdredd/src/mutation_replace_expr.cc
- test/single_file/space_needed_after_macro.c
- test/single_file/space_needed_after_macro.c.expected
- test/single_file/space_needed_after_macro.c.noopt.expected
- test/single_file/space_needed_after_macro2.c
- test/single_file/space_needed_after_macro2.c.expected
- test/single_file/space_needed_after_macro2.c.noopt.expected
Insert a space when mutating an expression directly after a macro expansion.
Fixes #239.
> Avoid problem with macro expansion

- .github/workflows/cxx_apps.sh
- src/libdredd/src/mutate_visitor.cc
- test/execute/switch_cases/harness.c
- test/execute/switch_cases/mutants.txt
- test/execute/switch_cases/original.txt
- test/execute/switch_cases/tomutate.c
- test/single_file/negative_switch_case.c.expected
- test/single_file/negative_switch_case.cc.expected
- test/single_file/negative_switch_case.cc.noopt.expected
- test/single_file/switch_cases1.c
- test/single_file/switch_cases1.c.expected
- test/single_file/switch_cases1.c.noopt.expected
- test/single_file/switch_cases2.c
- test/single_file/switch_cases2.c.expected
- test/single_file/switch_cases2.c.noopt.expected
Fixes a problem where statements appearing directly after 'case' and 'default' labels were not being mutated properly. Such statements were not being considered for removal, and an optimisation to avoid expression mutation was being missed for such statements.
Fixes #257.
> Mutate switch cases properly

- src/libdredd/include_private/include/libdredd/mutate_visitor.h
- src/libdredd/src/mutate_visitor.cc
- test/single_file/construct_struct_from_enum_constant.cc
- test/single_file/construct_struct_from_enum_constant.cc.expected
- test/single_file/construct_struct_from_enum_constant.cc.noopt.expected
Works around a special cases where mutating an enum constant that occurs in a C++ constructor can lead to ambiguity when used in a conditional expression.
Fixes #264.
> Avoid mutating enum constant in C++ constructor

- .github/workflows/cxx_apps.sh
- src/libdredd/include/libdredd/util.h
- src/libdredd/include_private/include/libdredd/mutate_visitor.h
- src/libdredd/src/mutate_visitor.cc
- src/libdredd/src/mutation_replace_expr.cc
- test/single_file/bitfield.c
- test/single_file/bitfield.c.expected
- test/single_file/bitfield.c.noopt.expected
- test/single_file/bitfield.cc
- test/single_file/bitfield.cc.expected
- test/single_file/bitfield.cc.noopt.expected
In preparation for fixing #259, this cleans up the code for deciding
when to ignore expressions that refer to bit-fields.
> Clean up handling of bit-fields

- README.md
- src/libdredd/src/mutate_visitor.cc
Updated the README to specify the supported Ubuntu version for the following shell commands. Additionally, fixed existing comments related to skipping switch case statement mutation because of previous AST traversal until no switch case is encountered. An assertion has been added to validate this behavior.
Implement reviewer suggestion on #260
Fix #217
> Update README for supported Ubuntu version and add assertion for switch case handling

- src/libdredd/include_private/include/libdredd/mutate_visitor.h
- src/libdredd/src/mutate_ast_consumer.cc
- src/libdredd/src/mutate_visitor.cc
- test/single_file/constexpr_array.cc
- test/single_file/constexpr_array.cc.expected
- test/single_file/constexpr_array.cc.noopt.expected
- test/single_file/static_constexpr_array.cc
- test/single_file/static_constexpr_array.cc.expected
- test/single_file/static_constexpr_array.cc.noopt.expected
Enhances the support for rewriting the size expressions of constant-sized arrays so that arrays with the constexpr qualifier are also handled.
Fixes #283.
> Rewrite size expressions of constant-sized constexpr arrays

- .github/workflows/cxx_apps.sh
- src/libdredd/src/mutate_visitor.cc
- test/single_file/initializer_list.cc.expected
- test/single_file/initializer_list_long_to_short.cc
- test/single_file/initializer_list_long_to_short.cc.expected
- test/single_file/initializer_list_long_to_short.cc.noopt.expected
- test/single_file/initializer_list_narrower.cc
- test/single_file/initializer_list_narrower.cc.expected
- test/single_file/initializer_list_narrower.cc.noopt.expected
Avoid bypass of implicit inner cast mutation under `default` (optimize_mutations) mode for expressions in Initializer List. Besides producing more mutants, this change ensures that Dredd can correctly handle narrowing type expressions involving `std::initializer_list` without bypassing necessary `static_cast` operations.
Fixes #270
> Prevent expression-under-cast-bypass in Initializer Lists for more mutations and narrowing type handling

- src/libdredd/src/mutation_replace_expr.cc
- test/single_file/initializer_list_parenthesis.cc
- test/single_file/initializer_list_parenthesis.cc.expected
- test/single_file/initializer_list_parenthesis.cc.noopt.expected
Fix a problem where expressions in parentheses within an initializer
list bypass being explicitly cast with `static_cast`, causing issues
when the expression is implicitly cast to a narrower type.
Fixes #301
> Avoid static cast bypass for parenthesis expression in initializer list

- src/libdredd/src/mutate_visitor.cc
- test/single_file/decltype_cast.cc
- test/single_file/decltype_cast.cc.expected
- test/single_file/decltype_cast.cc.noopt.expected
- test/single_file/decltype_cast_function_call.cc
- test/single_file/decltype_cast_function_call.cc.expected
- test/single_file/decltype_cast_function_call.cc.noopt.expected
Since Dredd's mutator functions don't change the type of expression,
mutating an expression under `Decltype` won't affect the outcome of
casting (i.e., they introduce equivalent mutation). Furthermore,
mutation of an expression under `Decltype` could introduce lambda
expression in the unevaluated operand.
Fixes #304
> Avoid mutation of expression under `Decltype`

- README.md
The troubleshooting section initially contains notes on bracket nesting depth and the need to tolerate warnings during compilation.
> Add troubleshooting section to documentation

- src/libdredd/include_private/include/libdredd/mutate_visitor.h
- src/libdredd/src/mutate_visitor.cc
- test/single_file/adl.cc
- test/single_file/adl.cc.expected
- test/single_file/adl.cc.noopt.expected
Identifies and avoids mutating various expressions that involve implicit casts from enums or class instances to primitive types, that might affect the outcome of argument-dependent lookup.
Fixes #296.
> Avoid mutations that break argument-dependent lookup (ADL)

- src/libdredd/src/mutate_visitor.cc
- test/single_file/nodiscard.cc
- test/single_file/nodiscard.cc.expected
- test/single_file/nodiscard.cc.noopt.expected
- test/single_file/nodiscard_macro.cc
- test/single_file/nodiscard_macro.cc.expected
- test/single_file/nodiscard_macro.cc.noopt.expected
- test/single_file/noreturn.cc
- test/single_file/noreturn.cc.expected
- test/single_file/noreturn.cc.noopt.expected
Uses libTooling's "associated range" facility to ensure that attributes are captured in the function source range before which Dredd's prelude should be written.
Fixes #318.
> Account for attributes when inserting prelude

- src/libdredd/include/libdredd/mutation_replace_expr.h
- src/libdredd/src/mutation_replace_expr.cc
- test/single_file/initializer_list_with_templates.cc
- test/single_file/initializer_list_with_templates.cc.expected
- test/single_file/initializer_list_with_templates.cc.noopt.expected
Fixes a problem where an explicit cast was not being added to a mutated expression in an initializer list where (after mutation) it is required. The logic to handle this was present, but was designed to expect the parents of the relevant AST node to have a specific order. This change generalises the logic to allow for multiple initializer list parents, because in the presence of templates a node may have two initializer list parents: one for the uninstantated version of the initializer list and the other for the instantiated version.
Fixes #321.
> Fix for issue with casts and initializer lists

- README.md
- src/dredd/src/main.cc
- src/libdredd/CMakeLists.txt
- src/libdredd/include/libdredd/mutation.h
- src/libdredd/include/libdredd/mutation_remove_stmt.h
- src/libdredd/include/libdredd/mutation_replace_binary_operator.h
- src/libdredd/include/libdredd/mutation_replace_expr.h
- src/libdredd/include/libdredd/mutation_replace_unary_operator.h
- src/libdredd/include/libdredd/new_mutate_frontend_action_factory.h
- src/libdredd/include/libdredd/options.h
- src/libdredd/include_private/include/libdredd/mutate_ast_consumer.h
- src/libdredd/include_private/include/libdredd/mutate_visitor.h
- src/libdredd/src/mutate_ast_consumer.cc
- src/libdredd/src/mutate_visitor.cc
- src/libdredd/src/mutation_remove_stmt.cc
- src/libdredd/src/mutation_replace_binary_operator.cc
- src/libdredd/src/mutation_replace_expr.cc
- src/libdredd/src/mutation_replace_unary_operator.cc
- src/libdredd/src/new_mutate_frontend_action_factory.cc
- src/libdreddtest/src/mutation_remove_stmt_test.cc
- src/libdreddtest/src/mutation_replace_binary_operator_test.cc
- src/libdreddtest/src/mutation_replace_expr_test.cc
- src/libdreddtest/src/mutation_replace_unary_operator_test.cc
Represents the values of various Dredd command line switches in a class, and adds another switch to allow AST node types to be output as comments in the mutated code, which is useful for debugging.
> Refactor options and add option for showing AST node types

- README.md
Describe common reasons and possible workarounds for Dredd's mutated
source file to fail to compile or cause a build failure, including the
lack of a compilation database and multiple conflicting compilation
contexts in the database
> Update README to debug compile/build failure
