mc-imperial/dredd

src/dredd/src/main.cc, src/libdredd/include/libdredd/new_mutate_frontend_action_factory.h, src/libdredd/include_private/include/libdredd/mutate_ast_consumer.h, src/libdredd/include_private/include/libdredd/mutate_visitor.h, src/libdredd/src/mutate_ast_consumer.cc, src/libdredd/src/mutate_visitor.cc, src/libdredd/src/mutation_replace_binary_operator.cc, src/libdredd/src/new_mutate_frontend_action_factory.cc, src/libdreddtest/src/mutation_replace_binary_operator_test.cc
The tool now mutates multiple files in place, and detects main (if
present), injecting code to initialise the selected mutant from an
environment variable.
=> Support multiple files and main

.github/workflows/dev_build.sh, src/libdredd/src/mutate_visitor.cc
=> Incorporate LLVM in CI.

AUTHORS, CONTRIBUTORS
Adds files to give credit to contributors to the project and to record
who holds copyright.
=> Add AUTHORS and CONTRIBUTORS files

.github/workflows/dev_build.sh
Check the given examples build and that the tests pass after mutation
(with no mutants applied).
Fixes #39.
=> Update CI to mutate and test given examples

src/libdredd/src/mutation_replace_expr.cc
=> Fix comment typos

src/libdredd/src/mutation_replace_binary_operator.cc
Adds a comment to justify why an assignment operator is not replaced by its LHS.
Fixes #96.
=> Comment on assignment operator replacement

README.md
=> Add details of --mutation-info-file flag to README

.github/workflows/build.sh, .github/workflows/build.yml, .github/workflows/release.sh, .github/workflows/release.yml, CMakeLists.txt, README.md, src/dredd/src/main.cc
=> Provide Dredd releases

.github/workflows/build.yml, README.md
Adds support for building under Windows in CI, and incorporates some CI refactorings.
=> Support Windows builds in CI

.github/workflows/build.sh, .github/workflows/build.yml, .github/workflows/c_apps.sh, .github/workflows/cxx_apps.sh, .github/workflows/dev_build.sh, src/libdredd/include/libdredd/mutation_replace_binary_operator.h, src/libdredd/include/libdredd/mutation_replace_expr.h, src/libdredd/include/libdredd/mutation_replace_unary_operator.h, src/libdredd/include/libdredd/protobufs/dredd.proto, src/libdredd/src/mutation_replace_binary_operator.cc, src/libdredd/src/mutation_replace_expr.cc, src/libdredd/src/mutation_replace_unary_operator.cc
Adds instance information for the mutations that are applied to the associated protobuf message.
=> Instance information for mutations

src/libdredd/include/libdredd/mutation_replace_binary_operator.h, src/libdredd/include/libdredd/mutation_replace_expr.h, src/libdredd/src/mutation_replace_binary_operator.cc, src/libdredd/src/mutation_replace_expr.cc, src/libdreddtest/src/mutation_replace_binary_operator_test.cc, src/libdreddtest/src/mutation_replace_expr_test.cc, test/single_file/logical_and.cc, test/single_file/logical_and.cc.expected, test/single_file/logical_and.cc.noopt.expected, test/single_file/logical_or.cc, test/single_file/logical_or.cc.expected, test/single_file/logical_or.cc.noopt.expected
=> Optimisations from literature

.github/workflows/build.sh, .github/workflows/build.yml, .github/workflows/c_apps.sh, .github/workflows/c_apps.yml, .github/workflows/cxx_apps.sh, .github/workflows/cxx_apps.yml, .github/workflows/dev_build.sh, .github/workflows/dev_build.yml, .github/workflows/install_clang.sh, .github/workflows/release.sh, .github/workflows/release.yml, dev_shell.sh.template
Also reinstates Windows and Mac builds in CI.
=> Use more recent Clang/LLVM version

src/libdredd/src/mutate_visitor.cc
=> Fix comments

.github/workflows/cxx_apps.sh, examples/threaded/src/producer.cc
=> Add threaded C++ example to CI

src/libdredd/src/mutate_visitor.cc, test/single_file/user_defined_literals.cc, test/single_file/user_defined_literals.cc.expected, test/single_file/user_defined_literals.cc.noopt.expected
=> Do not mutate user defined literals

.github/workflows/build.sh, src/libdredd/include_private/include/libdredd/mutate_visitor.h, src/libdredd/src/mutate_visitor.cc, test/single_file/do_not_mutate_under_alignof.cc, test/single_file/do_not_mutate_under_alignof.cc.expected, test/single_file/do_not_mutate_under_alignof.cc.noopt.expected, test/single_file/do_not_mutate_under_sizeof.c, test/single_file/do_not_mutate_under_sizeof.c.expected, test/single_file/do_not_mutate_under_sizeof.c.noopt.expected
=> Do not mutate under sizeof and alignof

scripts/query_mutant_info.py, test/execute/nomutants/harness.c, test/execute/nomutants/tomutate.c
=> Allow querying number of mutants when there are none

src/libdredd/src/mutate_visitor.cc, test/single_file/constexpr_if1.cc, test/single_file/constexpr_if1.cc.expected, test/single_file/constexpr_if1.cc.noopt.expected, test/single_file/constexpr_if2.cc, test/single_file/constexpr_if2.cc.expected, test/single_file/constexpr_if2.cc.noopt.expected
=> Do not mutate expression of constexpr if statement

scripts/query_mutant_info.py
=> Return -1 as largest mutant id if there are no mutants

scripts/check_one_execute_test.py
=> Pass extra C/C++ arguments to 'execute' tests

test/single_file/initializer_list_narrower_nested.cc.expected, test/single_file/initializer_list_narrower_nested.cc.noopt.expected
=> Fix single file test expections

src/libdredd/src/mutate_visitor.cc
Related issues: #219, #215
Related PR: #220
=> Remove redundant statement

src/libdredd/src/mutate_ast_consumer.cc, test/single_file/nested_array_with_named_constant_size_rewrite.cc, test/single_file/nested_array_with_named_constant_size_rewrite.cc.expected, test/single_file/nested_array_with_named_constant_size_rewrite.cc.noopt.expected
=> Handle nested arrays when rewriting static array sizes

README.md
=> Add documentation for mutant tracking mode

src/libdredd/src/mutate_ast_consumer.cc, test/single_file/nested_array_with_named_constant_size_rewrite.cc, test/single_file/nested_array_with_named_constant_size_rewrite.cc.expected, test/single_file/nested_array_with_named_constant_size_rewrite.cc.noopt.expected
=> Fix issue with array size rewriting

.github/workflows/cxx_apps.sh, src/libdredd/src/mutate_visitor.cc, test/single_file/vector_returns_temporary.cc.expected
=> Avoid redundant mutation arising from ExprWithCleanups nodes

src/dredd/src/log_failed_files_diagnostic_consumer.cc, src/dredd/src/main.cc, test/bespoke/nonexistent-file/test.py
=> Gracefully exit on non-existent file
